# https://github.com/savvyaxl/mosquito
version: '2.4'

services:
  ssl_client:
    build: ./
    container_name: mosquitto_ssl_client
    restart: on-failure:5
    ports:
      - 1883:1883
      - 8883:8883
    security_opt:
      - no-new-privileges
